# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
devices([
  "iPhone 11 Pro Max", # 6.5 inch display (1242x2688)
  "iPhone 8 Plus", # 5.5 inch display (1242x2208)
  "iPad Pro (12.9-inch) (4th generation)", # 2048x2732, 12.9 inch display without home button
  "iPad Pro (12.9-inch) (2nd generation)", # 2048x2732, 12.9 inch display with home button
])

# languages([
#   "en-US",
#   "de-DE",
#   "it-IT",
#   ["pt", "pt_BR"] # Portuguese with Brazilian locale
# ])

# The name of the scheme which contains the UI Tests
scheme("UI Test")

# Where should the resulting screenshots be stored?
output_directory("./screenshots")

# remove the '#' to clear all previously generated screenshots before creating new ones
clear_previous_screenshots(true)

# Remove the '#' to set the status bar to 9:41 AM, and show full battery and reception.
override_status_bar(true)

# Arguments to pass to the app on launch. See https://docs.fastlane.tools/actions/snapshot/#launch-arguments
launch_arguments([
  "-SELECTED_LEVEL 0 -SNAKE_PLAYERMODE twoPlayer_humanBot"
])

# For more information about all available options run
# fastlane action snapshot
